### PR TITLE
flutter

### PR DESCRIPTION
**Pull request by vishaljadhav207**

### CODE REVIEW

**Comment by riteshsonawane1372** [comment]
@vishaljadhav207 committed link ``https://mega.nz/folder/n8YDnIiA#E15euUFgJLURm_CxhrUKTQ`` has paid resources of Udemy, sorry we can't merge your pull request. Kindly add content that is free and open source.

**Comment by riteshsonawane1372** [comment]
Angel Yu Flutter course is outdated.

**Comment by vishaljadhav207** [comment]
it's free you can download those content from this folder or you can watch
online also. It's not paid anyway.

**Comment by adityasimant** [comment]
@riteshsonawane1372 can it be merged? Pls review and take actions.

**Pull request closed without merging**
